### ISSUE TITLE
EEWrap.h won't compile in Arduino Script

### ISSUE THREAD

**Issue by jbockh01** [Chris--A/EEWrap#1]
Error Message is as shown below

" /Arduino/libraries/EEWrap/EEWrap.h:71:122: error: template argument 2 is invalid
                 value = is_number<T>::value || is_bool<T>::value || is_same< T, wchar_t >::value || is_same< T, char16_t >::value
                                                                                                                          ^
Error compiling. "

placed in file with only #include <EEPROM.h> and #include <EEWrap.h> and still had issue. 

Also won't compile in basic test provided

**Comment by jbockh01** [comment]
Updated Arduino and Issue resolved itself

**Comment by Chris--A** [comment]
`char16_t` is a C++11 only variable type. Sorry, I didn't add it to the exclusions for C++98. Glad its resolved (C++11 enabled in IDE 1.6.6). I'll still fix up the code though, cheers.
